import Sidebar from "@/components/private/Sidebar"
import { createClient } from "@/lib/supabase/client"
import { redirect } from "next/navigation"
import PrivateNavbar from '@/components/private/PrivateNavbar'

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Griot | Dashboard",
  description: "Generated by create next app",
};



export default function RootLayout({ children }:{children:React.ReactNode}) {
    
    //added to remove those warnings its a temporary fix
  const conWarn = console.warn
  const conLog = console.log
  
  const IGNORE_WARNINGS = [
    'Using supabase.auth.getSession() is potentially insecure',
    'Using the user object as returned from supabase.auth.getSession()',
  ]
  
  console.warn = function (...args) {
    const match = args.find((arg) =>
      typeof arg === 'string' ? IGNORE_WARNINGS.find((warning) => arg.includes(warning)) : false,
    )
    if (!match) {
      conWarn(...args)
    }
  }
  
  console.log = function (...args) {
    const match = args.find((arg) =>
      typeof arg === 'string' ? IGNORE_WARNINGS.find((warning) => arg.includes(warning)) : false,
    )
    if (!match) {
      conLog(...args)
    }
  }
    
    const handleGetSessionUser = async () => {
      const supabase = createClient();
      const {
        data: { user },
      } = await supabase.auth.getUser();
      
      if (!user) {
        return redirect("/");
      }
    }

    handleGetSessionUser()
  
    
    return (
    <section className='relative w-full min-h-screen flex flex-row lg:gap-10 m-auto'>
             
      <Sidebar/>
      
      <section className='flex flex-col w-full bg-red-'>
        <PrivateNavbar/>
        <section className='flex flex-col items-center min-h-screen py-[2vh] mr-[2vw] ml-[2vw] lg:ml-[5vw] lg:mr-[1vw] 2xl:ml-[6vw] 2xl:mr-[2vw] '>
            {children}
        </section>
      </section>

    </section>
    )
}